# Generated by Django 5.0.1 on 2024-01-20 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0002_usermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='name',
            new_name='username',
        ),
    ]
