# Generated by Django 5.0.1 on 2024-01-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0003_rename_name_usermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='phoneNumber',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
