# Generated by Django 5.0.1 on 2024-01-21 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0006_todotaskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotaskmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todoList.usermodel'),
            preserve_default=False,
        ),
    ]
