# Generated by Django 5.0.1 on 2024-01-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0007_todotaskmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotaskmodel',
            name='user',
        ),
    ]
