# Generated by Django 5.0.1 on 2024-01-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0009_todotaskmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='token',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
