# Generated by Django 5.0.1 on 2024-01-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0010_remove_usermodel_token_alter_usermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.TextField(),
        ),
    ]
