# Generated by Django 5.0.1 on 2024-01-22 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0012_alter_todotaskmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='phoneNumber',
        ),
    ]
