# Generated by Django 5.0.1 on 2024-01-23 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0011_remove_usermodel_last_login'),
        ('todoList', '0013_remove_usermodel_phonenumber'),
    ]

    operations = [
    ]
